### ISSUE TITLE
Probezeit

### ISSUE THREAD

**Issue by ajuvo** [Chaostreff-Potsdam/satzungsentwurf#10]
Wenn keine Vereinsweite Bekanntmachung von Aufnahmegesuchen mit Widerspruchsmöglichkeit für Mitglieder (zur Abwehr in der Mitgliedschaft bekannter Querulanten), dann alternativ Probezeit für die Mitgliedschaft vorsehen (wie etwa auf der c-base, 6 Monate, während der man leicht wieder zu expedieren ist).

**Comment by chsterz** [comment]
Weiter unten steht ja, dass der Vorstand Mitglieder auch begründet ausschließen kann. 
Vielleicht reicht zusätzlich, dass der Vorstand auch sofort Nichtannahme erklären kann.

Ich sehe, eine Probezeit kann das begründen erleichtern, schafft aber unnötig Gefälle zw. Vollmitglied und Probemitglied.

**Comment by ajuvo** [comment]
rausschmiss ist niemals einfach; außer während einer probezeit. also in der praxis. es geht vor  allem geräuschlos. juristisch bedeutet probezeit, dass mitgliedschaft ohne voraussetzungen widerrufen werden kann.

**Comment by ajuvo** [comment]
und: rausschmiss während probezeit wegen inkompatibilität geht geräuschlos, ohne notwendigkeit einer bekanntmachung. das schützt auch den betroffenen, der ja nix verbrochen haben muss, außer mangelnder chaotoper kompatibilität.

**Comment by chsterz** [comment]
Mir gefällt der zweite Aspekt, dass es auch gesichtswahrend für die andere Person ist.

**Comment by cyroxx** [comment]
Just for reference: Ausgangspunkt für diesen Issue war der folgende Commit bzw. Commitkommentar: https://github.com/Chaostreff-Potsdam/satzungsentwurf/commit/ed6ec9539e7f95d371af86b425b2924c411a2634#commitcomment-33057274
