### ISSUE TITLE
Ermäßigter Beitrag für Rentner und Erwerbsgeminderte?

### ISSUE THREAD

**Issue by cyroxx** [Chaostreff-Potsdam/satzungsentwurf#13]
In anderen Beitragsordnungen sind auch Rentner, Erwerbsgeminderte und/oder Schwerbehinderte berechtigt, einen ermäßigten Beitrag zu zahlen.
Wollen wir diese Bevölkerungsgruppen (oder einen Teil davon) explizit mit aufnehmen?

**Comment by chsterz** [comment]
Klingt fair. Ich mach mal ein Pullrequest.
