### ISSUE TITLE
Präsenzveranstaltung entfernen & Stimmrechtsübertragungen zulassen ?

### ISSUE THREAD

**Issue by chsterz** [Chaostreff-Potsdam/satzungsentwurf#17]
Einfacher Fall: Mitglied A möchte Migtlied B aus Gründen (Behinderung, Verhinderung zur Versammlung) die Vollmacht übertragen an seiner statt zu entscheiden

Wir hatten das einfache Beispiel eines Mitglieds im Krankenhaus.
Ich denk Vollmachten sind fair. 

Stimmrechtsübertragung(Vollmacht) erfordert logischerweise das Abschaffen von Präsenzveranstaltung.

**Comment by chsterz** [comment]
Bitte Stimmt mit :+1:  oder :-1: damit wir ein bild haben. Plz begründen falls :-1:

**Comment by cyroxx** [comment]
Hmm, eine Vollmacht ist ja gerade das Mittel, um an einer Präsenzveranstaltung teilnehmen zu können. Die Möglichkeit, sich per Vollmacht vertreten zu lassen, bedingt gerade *nicht* die Abschaffung der Präsenzveranstaltung.

PS: Wo habt ihr den Teil mit "Präsenzveranstaltung" her?

**Comment by chsterz** [comment]
$4 S. 2
(2) Die Mitgliedsversammlung tritt mindestens einmal pro Kalenderjahr zusammen. Die Mitgliedsversammlung wird vom Vorstand mit einer Ladungsfrist von mindestens 14 Tagen und Angabe einer Tagesordnung schriftlich einberufen. issue: /* Mitgliedsversammlungen finden stets als Präsenzveranstaltung statt. */  Jedes Mitglied hat eine Stimme.

Verstehe, Ich dachte halt, meine Vollmacht ist unwirksam, weil ich ja nicht präsent bin.
Du siehst Präsenz eher als "kein Skype" ?

**Comment by cyroxx** [comment]
> Du siehst Präsenz eher als "kein Skype" ?

Jupp, das ist wohl eher als Abgrenzung zur "virtuellen Mitgliederversammlung" zu verstehen.
Siehe auch:
Die virtuelle Mitgliederversammlung im Verein (https://openslides.org/20121119)

Zur Vollmacht gibt es einige Dinge zu beachten, siehe etwa
https://www.vereinswelt.de/mitglieder-stimmrecht-delegieren
Sofern wir Vollmachten erlauben wollen (was ich durchaus unterstützen würde :+1: ), sollten wir dediziert regeln, wie das aussehen soll.

**Comment by chsterz** [comment]
Okay, also du plädierst für Präsenz ja, Vollmacht,ja(bedeutet aber gesonderten passus)

**Comment by cyroxx** [comment]
### Vollmacht
ja.

### Präsenz
Im Moment eher ja.

Grundsätzlich könnte ich mir vorstellen, eine Teilnahme übers Internet bzw. eine gänzlich virtuelle Mitgliedsversammlung zu ermöglichen. Das stünde uns als technikaffinem Verein gut zu Gesicht.

Bei der Vorstellung der Satzung diese Woche hatte ich arge technische und rechtliche Bauchschmerzen, was anderes als Präsenz zuzulassen. Es ist halt deutlich einfacher, Präsenz zu fordern.
Bei einer (ggf. teilweisen) virtuellen Mitgliedsversammlung müssten wir uns wahrscheinlich konkretere Gedanken um die Ausgestaltung machen. Videochat+Audio mit mehreren Teilnehmern stabil hinzubekommen ist nach meiner Erfahrung beispielsweise noch immer ein ziemlicher Krampf. Auch organisatorisch bedeutet es vermutlich einen gewissen Mehraufwand.

Immerhin gibt es rechtlich weniger Hürden als ich befürchtet habe (siehe die [Entscheidung des Oberlandesgerichtes (OLG) Hamm vom 27.09.2011 (Az.: I-27 W 106/11)](http://www.justiz.nrw.de/nrwe/olgs/hamm/j2011/I_27_W_106_11beschluss20110927.html)).

Ich sage nicht, dass es nicht geht, aber für mich sind zu viele Fragen offen als dass ich glaube, das wir uns bis Dienstag bzw. Mittwoch auf eine wie auch immer geartetete Form der (teilweisen) virtuellen Mitgliedsversammlung verständigen können.

Dann lasst uns das lieber aussparen und später über eine Satzungsänderung einfügen.

**Comment by chsterz** [comment]
Genau. Ich bin auch für Präsenz: ja, Vollmacht ja. (wenn Vollmacht dann möglich ist)

**Comment by ajuvo** [comment]
stimmübertragung und fernabstimmungen schaffen in der praxis anfechtungsgründe. im konfliktfall droht lähmung und vereinstod. diese ganzen regelungen sind ausfluss jahrzehntelanger praxis. müllt nicht darin rum. das gilt auch für manch anderes detail. ich habe jetzt keine zeit. wir ziehen das dienstag grade.

**Comment by chsterz** [comment]
Ganz ruhig, keine Angst. Die Idee von Github-Issues ist ja, das wir am Dienstag einen einfachen Job haben und schon ein Meinungsbild haben.

Präsenzpflicht ist ja im Aktuellen Diskussionsstand erhalten.

Das bedeutet, es geht gerade nur noch um das Ausstellen von Vollmachten das zur Debatte steht.
Klar hast du hier die längere Erfahrung, Aber genau so Traditionswissen muss dann auch für Leute die noch keinen Verein geleitet haben begründet werden, weil es sonst schlicht Arkanes Wissen ist.
