### ISSUE TITLE
Idealverein !?

### ISSUE THREAD

**Issue by chsterz** [Chaostreff-Potsdam/satzungsentwurf#18]
/? Der Verein ist nicht auf eigenwirtschaftliche Tätigkeit ausgerichtet und soll keine Gewinne erzielen, sondern vielmehr als Idealverein wirken.?/

@ajuvo was bedeutet das? Wir wollten ja schon (vor allem aus verminderten Stressgründen) nicht-gemeinnützig. Ist das nur aus ner anderen Satzung mit reingerutscht :) ?

**Comment by cyroxx** [comment]
IANAL, aber nach kurzem Querlesen geht es wohl darum, dass unser Hauptzweck nicht das Erzielen von Gewinnen ist (wirschaftlicher/Wirtschaftsverein), sondern das Verfolgen anderer Ideale (Bildung, Vernetzung, Verstehen von Technik, Basteln) im Vordergrund steht (Idealverein, nicht wirtschaftlicher Verein nach § 21 BGB).

Links:
* https://de.wikipedia.org/wiki/Idealverein
* https://www.iww.de/vb/archiv/idealverein-im-zivilrecht-das-nebenzweckprivileg-so-vermeidet-ein-verein-die-einstufung-als-wirtschaftsverein-f17806

**Comment by cyroxx** [comment]
Auszug aus dem BGB:

[§ 21 Nicht wirtschaftlicher Verein](https://www.gesetze-im-internet.de/bgb/__21.html)
> Ein Verein, dessen Zweck nicht auf einen wirtschaftlichen Geschäftsbetrieb gerichtet ist, erlangt Rechtsfähigkeit durch Eintragung in das Vereinsregister des zuständigen Amtsgerichts.

[§ 22 Wirtschaftlicher Verein](https://www.gesetze-im-internet.de/bgb/__22.html)
> Ein Verein, dessen Zweck auf einen wirtschaftlichen Geschäftsbetrieb gerichtet ist, erlangt in Ermangelung besonderer bundesgesetzlicher Vorschriften Rechtsfähigkeit durch staatliche Verleihung. Die Verleihung steht dem Land zu, in dessen Gebiet der Verein seinen Sitz hat.

**Comment by chsterz** [comment]
Okayyy. Das sieht stark danach aus, als macht das schon sinn mit dem Idealverein. 
Unsere ziele die wir anstreben sind ja Ideell und nicht wirtschaftlich.

**Comment by chsterz** [comment]
+ Supervielen Dank für die ausführliche Erklärung!

**Comment by ajuvo** [comment]
> /? Der Verein ist nicht auf eigenwirtschaftliche Tätigkeit ausgerichtet und soll keine Gewinne erzielen, sondern vielmehr als Idealverein wirken.?/
> 
> @ajuvo was bedeutet das? Wir wollten ja schon (vor allem aus verminderten Stressgründen) nicht-gemeinnützig. Ist das nur aus ner anderen Satzung mit reingerutscht :) ?

das muss so. nicht alle idealvereine sind gemeinnnützig. nicht ändern.
