### ISSUE TITLE
Quorum Für die Einberufung einer Mitgliederversammlung fehlt noch

### ISSUE THREAD

**Issue by chsterz** [Chaostreff-Potsdam/satzungsentwurf#19]
(3) Alle Vereinsmitglieder haben das Recht, vom Vorstand issue: quorum? unter Nennung gewünschter Tagesordnungspunkte und gegebenenfalls abzustimmender Beschlussvorlagen die Einberufung einer Mitgliedsversammlung zu verlangen, die binnen vier Wochen nach Eingang beim Vorstand stattzufinden hat.

**Comment by chsterz** [comment]
Ein fünftel, mindestens aber 4 Mitglieder zum Beispiel?

**Comment by ajuvo** [comment]
in der jetzigen version reicht halt eine/r. kann man erhöhen. zB auf drei.

**Comment by chsterz** [comment]
Ja. Deswegen habe ich das Issue aufgemacht. Soll nicht wegen einer einzelnen Idee alle antanzen müssen :)

Wäre mit "mindestens Drei Mitglieder" einverstanden.

**Comment by cyroxx** [comment]
> Eine Gemeinschaft **von mehr als drei Vereinsmitgliedern** hat das Recht, vom Vorstand [...] die Einberufung einer Mitgliederversammlung zu verlangen. 

(Auslassung und Hervorhebung von mir)

Damit haben wir jetzt ein Quorum von vier Mitgliedern, sehe ich das richtig?

Ich setzte diesen Issue mal auf Re-open, auf das Auffinden zu erleichtern.

**Comment by chsterz** [comment]
Danke für die Nachfrage.
Ja. Richtig. Drei war uns zu leicht. Zwei finden immer nen dritten für irgendwas.
Wenns mehr als das sind, dann sehen wir das als dazu würdig alle Mitglieder zur MV einzuladen.
Klar, wegen Aufwand sollen möglichst wenige MVs außerplanmäßig stattfinden.
