### ISSUE TITLE
Email und Telefonnummer für DSGVO

### ISSUE THREAD

**Issue by sirexeclp** [Chaostreff-Potsdam/satzungsentwurf#23]
Können wir bis Dienstag die Email-Adresse: datenschutz at domain
und eine Telefonnummer am Start haben.
Ist wichtig für DSGVO. s. #8 @chsterz @tzwenn

**Comment by chsterz** [comment]
Sollten wir hinkriegen

**Comment by chsterz** [comment]
Du kriegst dann meine Nummer

**Comment by tzwenn** [comment]
Mailbox am Start
