### ISSUE TITLE
Diskrepanz Vertretungsbefugnis

### ISSUE THREAD

**Issue by cyroxx** [Chaostreff-Potsdam/satzungsentwurf#24]
In der aktuellen Fassung (254a6e1) der Satzung sind der 1. und 2. Vorsitzende sowie der Schatzmeister jeweils einzeln vertretungsbefugt. Im Protokollentwurf für die Gründung hingegen gilt das nur für den 1. und 2. Vorsitzenden.

**Comment by DrSkyfaR** [comment]
Davon ausgehend das dass 4 Augen Prinzip gewahrt werden soll, sollte gar kein Vorstand alleine Vertretungsberechtigt sein.

**Comment by chsterz** [comment]
Also abstimmen soll er sich schon, der Vorstand. Wir wollen halt nur nicht immer zu dritt oder mehr zum Notar/Anwalt/Bank/Einkaufen/Gericht. 
klar könnte einer sich auch jedes Mal eine Vollmacht von den anderen beiden holen.

**Comment by chsterz** [comment]
@cyroxx Ja. Sollten wir eher im protokoll ändern.

**Comment by ajuvo** [comment]
es müssen mindestestens zwei leute einzeln vertretungsberechtigt sein. man kann und sollte das so machen, dass nur 1. und 2. vorsitzender vorstand im sinne des §26 BGB sind. sonst muss man bei jedem beisitzerwechsel zum registergericht.das  will man nicht.

**Comment by sirexeclp** [comment]
Also ich kenne es vom Förderverein meiner Grundschule (wo meine Mutter Geschäftsführerin war) auch so, dass die Leute einzeln Vertretungsberechtigt sind (zu viel Aufwand sonst). Wer als Vorstand gewählt wird hat sicherlich auch einen Vertrauensvorschuss verdient. Außerdem sind wir beim Chaos, da kommt doch nix weg.
