### ISSUE TITLE
Dokumente als Jinja Templates ?

### ISSUE THREAD

**Issue by sirexeclp** [Chaostreff-Potsdam/satzungsentwurf#26]
Wenn wir die Dokumente alle als Template machen:
z.B. statt `Chaos Computer Club Potsdam e. V.` immer `{{verein.name}}`, etc.
Hätten wir folgende Vorteile:

- einfache und konsistente Änderung von Daten wie: Adresse, Vorstände, etc.

- die Vorlage könnte einfacher auch von anderen Vereinen genutzt werden

- wir haben kein Problem mit dem Leaken von privaten Daten. Das Json-File mit den Variablen steht im .gitignore. Dazu ein build-Verzeichnis welches ebenfalls ignoriert wird.

- Verwendung von 2 Json-Files getrennt nach private und öffentliche Daten.

Wahrscheinlich total over-engineered. Python Skript hätte ich schon fertig.
Oder lassen wir es lieber so, wie es jetzt ist?

**Comment by chsterz** [comment]
Naja, wir machen ja jetzt nicht jeden Tag ne Satzung fertig.
Kannst das ja fürs Protokoll machen. 

Es gilt der Grundsatz, das soll vorrangig stress mindern und fun erhöhen :)

**Comment by chsterz** [comment]
Gute Idee aber generell!
