### ISSUE TITLE
BO: Förder- und Ehrenmitgliedschaften?

### ISSUE THREAD

**Issue by tzwenn** [Chaostreff-Potsdam/satzungsentwurf#28]
Andere diskutierte Optionen zum Beitrag:

* Ehrenmitglieder (keine Zahlung, Stimmrecht)
* Fördermitglieder (Zahlung, kein Stimmrecht)
(verlangen Link in Satzung)

Außerdem, weniger dringend: Sollte die BO auch Härtefallregelungen für Beträge <9€ in Absprache ermöglichen?

**Comment by chsterz** [comment]
Wird langsam ganz schön lang.
Prinzipiell sind Ehrenmitglieder ok (würds aber später erst einführen)
Fördermitglieder auch.

Ich bin gegen Beitragsausnahmen unter 9 €. 
Das muss schaffbar sein. Sind 2.25 pro Treffen. Und es gibt meistens Essen. Sorry.

**Comment by tzwenn** [comment]
zu oben: okay, diskussion verschoben

zu <9€ verstehe. Und Treff, wie du sagtest sowieso offen. Geht um den Beitrag zu den Perks+X
