### ISSUE TITLE
Limit für Umlagen in Satzung?

### ISSUE THREAD

**Issue by tzwenn** [Chaostreff-Potsdam/satzungsentwurf#29]
Wenn wir Umlagen erheben wollen sollte das per Satzung möglich sein 

und *sollte* eine Obergrenze festgelegt werden [II ZR 91/06   (a)](http://juris.bundesgerichtshof.de/cgi-bin/rechtsprechung/document.py?Gericht=bgh&Art=en&nr=41785&pos=0&anz=1)

Formulierungsvorschlag:

(X) Zur Finanzierung besonderer Vorhaben oder zur Beseitigung finanzieller Schwierigkeiten des Vereins können von den Mitgliedern Umlagen erhoben werden. Über die Notwendigkeit, Höhe und Fälligkeit von Umlagen und den Kreis der zahlungspflichtigen Mitglieder entscheidet die Mitgliederversammlung mit der einfachen Mehrheit der abgegebenen Stimmen. Die Höhe der Umlage darf das 6-fache des Mitgliedsbeitrags nichts übersteigen. Maßgebend ist der Jahresbeitrag, den das zahlungsverpflichtete Mitglied zum Zeitpunkt der Beschlussfassung über die Erhebung der Umlage zu zahlen hat.

**Comment by sirexeclp** [comment]
6*Mitgliedsbeitrag wäre dann
8,56€ für Kinder
54€ für Arme
80,22€ für Studenten
140,52€ für "Normalos"

Persönlich fände ich das so in Ordnung. Nur würde ich denken, dass vor allem die Gruppen, die nicht den Vollpreis zahlen es möglicher weise schwer finden dann auf einmal das Geld aufzubringen.
Andererseits ist es ja nur eine Obergrenze, muss man ja nicht immer voll ausschöpfen.
Anders ausgedrückt wäre es dann eine Beitragserhöhung auf 150% für ein Jahr gerechnet, also durchaus verschmerzbar.

**Comment by tzwenn** [comment]
* `und den Kreis der zahlungspflichtigen Mitglieder`, erlaubt ggf. Rücksicht auf Härtefälle
* genau, ist maximum. Erfüllt die somit die gerichtliche Anforderung
