### ISSUE TITLE
Stimmrecht für Juristische Personen zulassen?

### ISSUE THREAD

**Issue by chsterz** [Chaostreff-Potsdam/satzungsentwurf#30]
Sagt eure Meinung.

Eine Möglichkeit wäre Vollmitgliedschaft.
Eine andere eine (stimmlose) Fördermitgliedschaft.

Das dahinter stehende Poblem:
Wollen wir zulassen dass ein reguläres Miglied, weil sie Vertreter einer jur. Person ist quasi 2 Stimmen hat? Man könnte sich so eine zweite Stimme "kaufen" wenn man wie ich beispielsweise eine Firma hat.

**Comment by sirexeclp** [comment]
Aber wie viele Leute gründen eine Firma bzw. haben eine und würden das dann ausnutzen um eine 2. Stimme haben zu können? (Risiko-nutzen Abwägung)
Kann man es nicht so machen, dass eine Vollmitgliedschaft als jur. Person nur möglich ist, wenn der Eigentümer der Firma nicht bereits privat Mitglied ist.

**Comment by chsterz** [comment]
Frage ist eher: Für was stimmt eine juristische Person in unserem Verein dann ab? Neue Beleuchtung? Gemeinsamer Grillabend? $Kunst fürs Camp?

klar, sowas wie Abstimmung über Vorstand im Sinne der jur. Pers. , das mach noch so halb sinn.

**Comment by tzwenn** [comment]
Stimmungsbild im AK Satzung: Firmenmitglieder kommen raus.
