### ISSUE TITLE
Definition Geschäftsjahr ist unklar.

### ISSUE THREAD

**Issue by tzwenn** [Chaostreff-Potsdam/satzungsentwurf#32]
Vorschlag unter §1 oder (besser?) §7:

(X) Das Geschäftsjahr entspricht dem Kalenderjahr.

**Comment by sirexeclp** [comment]
> (X) Das Geschäftsjahr entspricht dem Kalenderjahr.

~~Gibt es etwas, was dagegen spricht ?~~
Gegenvorschlag: Wir orientieren uns am Semester(ende), da viele Mitglieder[citation needed] Studenten sind und daher mutmaßlich zu Beginn / Ende der Semester Mitglieder wegziehen bzw. neue hinzukommen.

**Comment by tzwenn** [comment]
Verstehe deine Studisicht. Langfristig, kommen aber (hoffentlich) nicht nur Studis.
Familien ziehen oft mit den Schuljahren um.
(Miet)verträge, Finanzspielereien und die Welt ringsherum spielt eher Kalenderjahre.
