### ISSUE TITLE
Was ist ein Beisitz?

### ISSUE THREAD

**Issue by tzwenn** [Chaostreff-Potsdam/satzungsentwurf#34]
ggf am Dienstag klären:
* Was ist der Beirat?
* Ist ein Beirat Vorstandsmitglied?

Der Text ist momentan unsauber an der Stelle (vgl §6 (3), (4)).

**Comment by chsterz** [comment]
Ist mir auch unklar. Brauchen wir sowas? --> Dienstag klären.

**Comment by cyroxx** [comment]
Was genau ist das Problem? Ich konnte das Wort "Beirat" nicht in unserer Satzung finden.

**Comment by tzwenn** [comment]
`s/Beirat/Beisitz/`
