### ISSUE TITLE
Protokoll: Tagesordnung (y/n)

### ISSUE THREAD

**Issue by sirexeclp** [Chaostreff-Potsdam/satzungsentwurf#39]
Wollen wir zu Beginn der Versammlung über eine Tagesordnung abstimmen?
Das gibt dem ganzen etwas mehr Formalität und Struktur finde ich.
(war in @ajuvo s protokoll nicht vorgesehen in dem vom @ApoRes1337 schon.

Falls ja: Soll es zu Beginn noch eine Aussprache zur Gründung geben (so eine art Einleitung) bzw. Begründung mit Zweck des Vereins etc. ?

**Comment by tzwenn** [comment]
Ja, ich denke das ist notwendig.

Und ja, gremientreffen beginnen immer mit einer Begrüßung :)
