### ISSUE TITLE
Anwesenheitsliste

### ISSUE THREAD

**Issue by sirexeclp** [Chaostreff-Potsdam/satzungsentwurf#41]
# Anlage 1: Anwesenheitsliste

|Vorname|Name|Geburtsdatum|Adresse|Unterschrift|
|-------|----|------------|-------|------------|
|Max|Mustermann|X.Y.Z|Adresse goes here|XXX|
| | | | | | 
| | | | | | 
| | | | | | 
| | | | | | 
| | | | | | 
| | | | | | 

@chsterz @tzwenn @cyroxx @ApoRes1337 @ajuvo 
Passt das so ?
Brauchen wir Beruf oder kann die Spalte noch weg?

Unterzeichnet die Liste der Vorstand oder Protokollführer und Sitzungsleiter?
*Edit: Beruf entfernt

**Comment by chsterz** [comment]
Ich würds weglassen.

**Comment by chsterz** [comment]
Hier https://deutsches-ehrenamt.de/verein-gruenden/die-vereinsgruendung/ steht es beispielsweise nur für den Vorstand drin.

**Comment by sirexeclp** [comment]
> Hier https://deutsches-ehrenamt.de/verein-gruenden/die-vereinsgruendung/ steht es beispielsweise nur für den Vorstand drin.

Hmm.
Ich würde es zumindest am Dienstag noch mal kurz ansprechen.

**Comment by cyroxx** [comment]
Es geht um die Anwesenheitsliste für die Gründungsversammlung?

Generell bin ich für Datensparsamkeit. Kann aber sein, dass man den Beruf für den Notar bzw. das Vereinsregister braucht.

**Comment by DrSkyfaR** [comment]
Für die Eintragung im VEreinsregister werden Vorname + Nachname, Geburtsdatum und komplette Anschrift benötigt

**Comment by DrSkyfaR** [comment]
Achso das Protokoll wird vom Schriftführer und Versammlungsleiter unterschrieben am Ende.

**Comment by pluehne** [comment]
@sirexeclp: Ich hab basierend auf deiner Vorlage eine Anwesenheitsliste gebaut: https://files.ccc-p.org/dokumente/anwesenheitsliste-gruendungsversammlung.pdf ([Quelldateien](https://github.com/Chaostreff-Potsdam/office/tree/master/dokumente/anwesenheitsliste-gruendungsversammlung)). Passt das so?
