### ISSUE TITLE
Festlegen monatlich kündbar.

### ISSUE THREAD

**Issue by chsterz** [Chaostreff-Potsdam/satzungsentwurf#47]
Gerade für Studenten, die dann ein Semester nicht da sind.

**Comment by chsterz** [comment]
Haben mich mehrere Studis gebeten.

**Comment by DrSkyfaR** [comment]
Macht die langfristige finanzielle Planung aber deutlich schwieriger das mag Bedacht werden. :) 
Gerade bei den größeren jährlichen Posten sollte man das nicht außer acht lassen.
