### ISSUE TITLE
BO: Datum?

### ISSUE THREAD

**Issue by cyroxx** [Chaostreff-Potsdam/satzungsentwurf#65]
Sollte/muss die Beitragsordnung noch ein Datum bekommen zu Versionierungsgründen/Referenzierungsgründen?

**Comment by pluehne** [comment]
Hat sie in der finalen PDF dann :slightly_smiling_face:.

**Comment by pluehne** [comment]
@cyroxx: Hier übrigens die aktuelle PDF-Version: https://files.ccc-p.org/dokumente/beitragsordnung.pdf.
