### ISSUE TITLE
Beschlussfähigkeit des Vorstands

### ISSUE THREAD

**Issue by cyroxx** [Chaostreff-Potsdam/satzungsentwurf#66]
Ein Punkt, der mir nach Lesen von
https://www.vereinswelt.de/erweiterter-vorstand
noch unspezifiziert scheint: Wann ist der Vorstand beschlussfähig?

Vorschlag: "Eine Vorstandssitzung ist beschlussfähig, wenn mehr als die Hälfte aller stimmberechtigten Vorstandsmitglieder anwesend sind."

**Comment by chsterz** [comment]
The honourable member will be heard! :)

**Comment by tzwenn** [comment]
The right honourable member has made his point very clear. Now let us hear what the house has to say.

**Comment by chsterz** [comment]
OOOrder :)
