### ISSUE TITLE
Vorstand: Absatz zu Beratern 

### ISSUE THREAD

**Issue by cyroxx** [Chaostreff-Potsdam/satzungsentwurf#67]
Mir ist noch nicht abschließend klar, was genau der § 6 Abs. (3) bezwecken soll bzw. ob er von allen gleich verstanden wird: 

> (3) Der Vorstand kann einzelne Personen als Berater hinzuziehen, diese haben dann kein Stimmrecht im Vorstand. Die Einberufenen können bestimmen, dass die Sitzung mittels fernmündlicher oder sonstiger Nachrichtenübermittlung geschieht. Über die Beschlüsse ist eine Niederschrift anzufertigen, die allen Vorstandmitgliedern binnen einer Woche nach der Sitzung zuzustellen ist.

Ich habe den Eindruck, dass hier zwei Dinge vermischt werden, die unabhängig voneinander sind:
1. Die Möglichkeit, Berater hinzuzuziehen, sowie
2. Die allgemeinen Formalien, die für jede Vorstandssitzung gelten sollen (unabhängig von irgendwelchen Beratern).

_Hinweis: In einer früheren Version war vom Einberufenden (derjenige, der die Sitzung einberuft; aktiv) die Rede, jetzt von den Einberufenen (die, die zur Sitzung zusammenkommen - die Vorstandsmitglieder? Oder sind hier nur die Berater gemeint?)_

Sofern ich das richtig verstehe, plädiere ich dafür, dass wir den Absatz auftrennen und leicht umstrukturieren. Ich mache mal noch einen PR dafür auf.

Sorry, dass ich erst jetzt damit ankomme, aber lieber jetzt als nach der Gründungsversammlung...

**Comment by chsterz** [comment]
Ich finde den Pullrequest hierzu gut, 
Schließe das issue sobald er durch ist.
