### ISSUE TITLE
Datenschutzerklärung hinzufügen

### ISSUE THREAD

**Issue by chsterz** [Chaostreff-Potsdam/satzungsentwurf#8]
Vor Mitgliedschaftserklärung muss jede/r Beitretende/r über den Datenschutz informiert sein. 
@sirexeclp hattest du etwas auf dem Stick erhalten?

**Comment by sirexeclp** [comment]
Ich hab mir aus ~~Dummheit~~ übertriebener Datensparsamkeit nur das Protokoll kopiert.
Ich kann aber mal im Internet was raussuchen.
https://www.freeprivacypolicy.com/builder/download/retrieve?token=37ed9fb11dc452ddf13be1e2063836c6

**Comment by ajuvo** [comment]
auf die Rückseite der Beitrittserklärung drucken

**Comment by sirexeclp** [comment]
ok das was ich da habe ist eher für websites
@ajuvo hast du zufällig eine GDPR konforme Erklärung zur hand ?

**Comment by ajuvo** [comment]
leider nein

**Comment by sirexeclp** [comment]
Hier mal das was ich beim *großen* CCC gefunden habe:
Quellen:
https://www.ccc.de/de/datenschutz
https://www.ccc.de/de/faq#gespeicherte_daten

Datenschutzerklärung
Verantwortlicher für die Erhebung, Verarbeitung und Nutzung Ihrer personenbezogenen Daten im Sinne von Art. 4 Nr. 7 DSGVO ist

    Chaos Computer Club e. V.
    Zeiseweg 9
    D-22765 Hamburg
    Germany
Betroffenenrechte: Rechte auf Auskunft, Berichtigung, Sperre, Löschung und Widerspruch
Sie haben das Recht, auf Antrag unentgeltlich eine Auskunft über die bei uns gespeicherten personenbezogenen Daten anzufordern und/oder eine Berichtigung, Sperrung oder Löschung zu verlangen. Eine Sperrung oder Löschung kann nicht erfolgen, wenn gesetzliche Regelungen dem entgegenstehen.

Bitte kontaktieren Sie unseren Datenschutzbeauftragten unter datenschutz@ccc.de.

Datenvermeidung und Datensparsamkeit
Wir speichern gemäß den Grundsätzen der Datenvermeidung und Datensparsamkeit personenbezogene Daten nur so lange, wie dies erforderlich ist oder vom Gesetzgeber vorgeschrieben wird.

Erfassung allgemeiner Informationen
Informationen zu einem Zugriff auf unseren Internetauftritt werden grundsätzlich nicht automatisiert (in Form von Logfiles) erfasst. Für administrative Zwecke kann eine kurzfristige Erstellung von Logfiles notwendig werden. Die Logfiles werden in diesem Fall anschließend gelöscht. Die Logfiles sind von allgemeiner Natur und erlauben keine Rückschlüsse auf Ihre Person.

Sofern Logfiles erstellt werden, können unter anderem folgende Datenarten erfasst werden: IP-Adresse und Datum.

Mailinglisten
Die Daten, die Sie für die Anmeldung an einer oder mehrerer Mailinglisten angegeben haben, werden von uns ausschließlich für diesen Zweck verwendet. Es werden keine Daten an Dritte weitergegeben.

Welche Daten werden gespeichert ?
 Name, Anschrift, E-Mail, PGP-ID, Eintrittsdatum, „Bezahlt bis“-Datum, „zuletzt gezahlt“-Datum, ermäßigt-/Vollzahler-Status, ggf. Kommentar. Diese werden Dir mit auf anfrage per E-Mail von uns als sogenannter Datenbrief zugesendet.

F: Wie kann ich meine bei Euch hinterlegten Daten ändern/aktualisieren?
A: Sende eine E-Mail mit Deiner Chaosnummer, Deinem Namen und den neuen Daten an das Office.

**Comment by santifa** [comment]
Es steht zwar schon implizit drin, aber ein Passus was beim Austritt mit den Daten passiert wäre noch gut. Also welche steuerrechtlich gespeichert werden müssen über 10 Jahre und welche vorher entfernt werden/können.

Desweiteren fehlt mMn noch der Erhebungsgrund (Mitgliederverwaltung) und der Einwilligungsteil mit Datum und Unterschrift bzw automatische Einwilligung bei Beitritt.
Und ab 9 Leuten im Vorstand bräuchte man sicher einen Datenschutzbeauftragten.

**Comment by chsterz** [comment]
Wow, Danke für die Hilfe :blush:

**Comment by chsterz** [comment]
@sirexeclp Hatteste das von @santifa schon drin?
Wenn du das hast, dann close ich das Issue.

**Comment by sirexeclp** [comment]
> @sirexeclp Hatteste das von @santifa schon drin?
> Wenn du das hast, dann close ich das Issue.

Ja, ich habe jeweils noch einen Satz dazu geschrieben.
Da sollten wir aber nochmal drüber schauen ob das ausreichend ist.

**Comment by DrSkyfaR** [comment]
Ich bin da mal nicht so :) 

Informationsblatt Datenschutz

Sehr geehrtes Mitglied,
wir sind gemäß DSGVO dazu verpflichtet, sie über die Verarbeitung Ihrer Daten im Verlaufe unserer vor-vertraglichen und vertraglichen Maßnahmen zu informieren. Bitte nehmen Sie sich einen Moment Zeit um dieses Informationsblatt durchzulesen.
_____________________________________________________________
I. Kontakt & Verantwortlicher:
Vereinsname
c/o vertretungsberechtigter Vorstand
Anschrift
Tel:
Mail

_____________________________________________________________
II. Rechtsgrundlagen
Wir werden Ihre Daten aus folgenden Gründen rechtmäßig verarbeiten:
    I. Basierend auf Ihrer ausdrücklichen Einwilligung zur Verarbeitung der Sie betreffenden personenbezogenen Daten. (Artikel 6 Absatz 1 a) DSGVO). Sie haben das Recht diese Einwilligung jederzeit zu widerrufen, ohne dass die Rechtmäßigkeit der aufgrund der Einwilligung bis zum Widerruf erfolgten Verarbeitung berührt wird;
    II. zur Erfüllung unserer vertraglichen Verpflichtungen (Artikel 6 Absatz 1 b) DSGVO); 
    III. zur Durchführung vor-vertraglicher Maßnahmen (Artikel 6 Absatz 1 b) DSGVO);
    IV. zur Wahrung gesetzlicher Pflichten (Artikel 6 Absatz 1 c) DSGVO);
       
Außerdem werden wir Ihre Daten aufgrund des berechtigten Interesses unseres Vereins (Artikel 6 Absatz 1 f) DSGVO) verarbeiten, diese sind:
    I.  Interne Verwaltung / Notwendige Korrespondenz
    II.  Buchhaltung
    III. Geltendmachung, Ausübung oder Verteidigung rechtlicher Ansprüche
       
_____________________________________________________________



III. Datenverarbeitung Mitgliedschaft
    1. Kontaktdaten: Name, Volle Adresse, E-mail Adresse 
    2. Finanzdaten: IBAN, BIC, Bankinstitut 
    3. Sonstige Daten: Bescheinigungen (Anspruchsnachweis, Spendenquittung etc.), Ehrenamtliche Tätigkeiten für den Verein
Die von Ihnen bereit gestellten Daten sind zur Vertragserfüllung bzw zur Durchführung vor-vertraglicher Maßnahmen erforderlich. Ohne diese Daten können wir den Vertrag mit Ihnen nicht abschließen. Die Angabe von Finanzdaten (SEPA Lastschrift) und die Erbringung eines Anspruchsnachweises für Ermäßigungen des Mitgliedsbeitrages sind nicht zwingend erforderlich und als optional anzusehen.
Ihre Daten werden bei uns nur solange gespeichert wie es für die jeweiligen Zwecke notwendig ist, für den wir Ihre Daten erhoben haben. Es ist allerdings zu Berücksichtigen das wir aus rechtlichen Gründen Rechnungen, relevante Verträge und sonstige Dokumente für 6 oder 10 Jahre aufbewahren müssen. Es kann vorkommen dass die Speicherdauer länger als zehn Jahre beträgt, etwa bei anhängigen Behördenverfahren. Wir werden sie in diesem Fall gesondert darüber informieren.
Wir haben entsprechende Autorisierungsstrukturen implementiert und Verschwiegenheitsverpflichtungen mit jenen Personen abgeschlossen die Zugriff auf diese Daten haben.
_____________________________________________________________
IV. Datenverarbeitung Kontaktaufnahme
Eine Kontaktaufnahme über die bereitgestellten E-Mail-Adressen ist möglich. In diesem Fall werden die mit der E-Mail übermittelten personenbezogenen Daten des Nutzers gespeichert. Es erfolgt in diesem Zusammenhang keine Weitergabe der Daten an Dritte. Die Daten werden ausschließlich für die Verarbeitung der Konversation bzw. des Anliegens verwendet.

Die Verarbeitung der personenbezogenen Daten dient uns allein zur Bearbeitung der Kontaktaufnahme. Im Falle einer Kontaktaufnahme per E-Mail liegt hieran das erforderliche berechtigte Interesse an der Verarbeitung der Daten. Die sonstigen während des Absendevorgangs verarbeiteten personenbezogenen Daten dienen dazu, die Sicherheit unserer informationstechnischen Systeme sicherzustellen.

Die Daten bleiben maximal 3 Monate ab Beendigung der Korrespondenz gespeichert, es sei denn es bestehen gesetzliche Verpflichtungen, ein berechtigtes Interesse unsererseits oder sonstige vertragliche Verpflichtungen.
Der Nutzer hat jederzeit die Möglichkeit, seine Einwilligung zur Verarbeitung der personenbezogenen Daten zu widerrufen.
Nimmt der Nutzer per E-Mail Kontakt mit uns auf, so kann er der Speicherung seiner personenbezogenen Daten jederzeit widersprechen. In einem solchen Fall kann die Konversation nicht fortgeführt werden.

Sollte der Nutzer der Speicherung der Daten widersprechen wollen, kann der Widerspruch via E-Mail eingereicht werden. Alle personenbezogenen Daten, die im Zuge der Kontaktaufnahme gespeichert wurden, werden in diesem Fall gelöscht.
_____________________________________________________________
V. Datenverarbeitung Newsletter
Wir versenden regelmäßig Newsletter, an Mitglieder, mit Neuigkeiten und Informationen über den Verein und dessen Tätigkeiten.
Der Newsletter kann nur empfangen werden wenn wir eine gültige Einwilligung, z.B. im Rahmen des Mitgliedsantrags, erteilt bekommen und eine E-mail Adresse angegeben wurde. In diesem Fall wird die E-mail Adresse und die Einwilligung gespeichert. Wir senden vorab eine zusätzlich E-mail um zu Überprüfen, ob die E-mail Adresse gültig und der Inhaber des Kontos die Einwilligung erteilt hat. (Double Opt In Verfahren)
Es erfolgt in diesem Zusammenhang keine Weitergabe der Daten an Dritte. Die Daten werden ausschließlich für den Versand des Newsletters verwendet.
Die Daten bleiben bis zur Abmeldung gespeichert, es sei denn es bestehen gesetzliche Verpflichtungen, ein berechtigtes Interesse unsererseits oder sonstige vertragliche Verpflichtungen.
Der Nutzer hat jederzeit die Möglichkeit, seine Einwilligung zur Verarbeitung der personenbezogenen Daten zu widerrufen. Dafür genügt eine formlose E-mail an Email Adresse , mit dem Wort „Abmeldung Newsletter“. Ein entsprechender Hinweis zur Abmeldung befindet sich zusätzlich in jedem Newsletter.
_____________________________________________________________
VI. Auftragsverarbeiter:
    1. Serverhoster XYZ: Serverhosting. Sämtliche Daten, die durch Anbieten von Servern, Kontaktmöglichkeiten, Verwaltungssystemen und der Websiten des Vereins anfallen, werden auf Serversystemen von Serverhoster gespeichert. Verantwortlicher des Unternehmens ist Name, Straße in PLZ Ort.
Entsprechende Verträge zur Auftragsverarbeitung liegen vor.
Es findet keine Datenübermittlung in Drittländer außerhalb des EWR-Raumes statt.
_____________________________________________________________
VII. Rechte der betroffenen Person:
1. Auskunftsrecht 
Sie können von dem Verantwortlichen eine Bestätigung darüber verlangen, ob personenbezogene Daten, die Sie betreffen, von uns verarbeitet werden. 
Dazu zählen unter anderem: Kategorie der personenbezogenen Daten, Empfänger, Verarbeitungszwecke, Speicherdauer, Herkunft (sofern die Daten aus Drittquellen kommen), Informationen über automatisierte Entscheidungsfindung, deren Details und ggf. Profiling. (Wir führen die beiden letzten Punkte nicht durch)
Ausserdem können sie Auskunft über Ihre Rechte (Beschwerderecht, Löschung, Berichtigung, Einschränkung der Verarbeitung )verlangen. 

2. Recht auf Berichtigung 
Sie haben ein Recht auf Berichtigung und/oder Vervollständigung gegenüber dem
Verantwortlichen, sofern die verarbeiteten personenbezogenen Daten, die Sie betreffen, unrichtig oder unvollständig sind. Der Verantwortliche hat die Berichtigung unverzüglich vorzunehmen.

3. Recht auf Einschränkung der Verarbeitung und Löschung
Sie können die Einschränkung der Verarbeitung der Sie
betreffenden personenbezogenen Daten verlangen, wenn Sie die Richtigkeit bestreiten, die Verarbeitung unrechtmäßig ist und Sie die Löschung ablehnen und stattdessen die Einschränkung der Nutzung verlangen, wir diese Daten nicht mehr benötigen, Sie diese jedoch zur Geltendmachung, Ausübung oder Verteidigung von Rechtsansprüchen benötigen, oder wenn Sie Widerspruch gegen die Verarbeitung gemäß Art. 21 Abs. 1 DSGVO eingelegt haben.
Sie können weiters von dem Verantwortlichen verlangen, dass die Sie betreffenden personenbezogenen Daten unverzüglich gelöscht werden, und der Verantwortliche ist verpflichtet, dies zu tun, außer die Verarbeitung ist erforderlich zur Ausübung des Rechts auf freie Meinungsäußerung und Information; zur Erfüllung einer rechtlichen Verpflichtung, aus Gründen des öffentlichen Interesses, zur Geltendmachung, Ausübung oder Verteidigung von Rechtsansprüchen. 

4. Recht auf Datenübertragbarkeit 
Sie haben das Recht, die Sie betreffenden personenbezogenen Daten, die Sie dem
Verantwortlichen bereitgestellt haben, in einem strukturierten, gängigen und maschinenlesbaren Format zu erhalten. Außerdem haben Sie das Recht diese Daten einem anderen Verantwortlichen übermitteln zu lassen.

5. Widerspruchs und Widerrufsrecht 
Sie haben das Recht, Ihre datenschutzrechtliche Einwilligungserklärung jederzeit zu widerrufen. Durch den Widerruf der Einwilligung wird die Rechtmäßigkeit der aufgrund der Einwilligung bis zum Widerruf erfolgten Verarbeitung nicht berührt.
Sie haben ebenso das Recht, aus Gründen, die sich aus ihrer besonderen Situation ergeben, jederzeit gegen die Verarbeitung der Sie betreffenden personenbezogenen Daten, die aufgrund von Art. 6 Abs. 1 lit. e oder f DSGVO erfolgt, Widerspruch einzulegen.

Werden die Sie betreffenden personenbezogenen Daten verarbeitet, um Direktwerbung zu
betreiben, haben Sie das Recht, jederzeit Widerspruch gegen die Verarbeitung zum Zwecke derartiger Werbung einzulegen.

6. Recht auf Beschwerde bei einer Aufsichtsbehörde 
Ihnen steht das Recht auf Beschwerde bei einer Aufsichtsbehörde zu, wenn Sie der Ansicht sind, dass die Verarbeitung der Sie betreffenden personenbezogenen Daten gegen die DSGVO verstößt. Sie können sich grundsätzlich an die zuständige Aufsichtsbehörde Ihres Wohnortes oder Arbeitsplatz wenden. 
_____________________________________________________________
VIII. Schlussworte:
Wir hoffen das wir Ihnen mit diesen Informationen Klarheit über die Prozesse verschafft haben. Sollten Sie noch Fragen zur Verarbeitung Ihrer Daten haben oder andere Anliegen die dieses Thema betreffen, zögern Sie nicht sich an uns zu wenden.

Stand: XX.XX.XX

**Comment by sirexeclp** [comment]
Vielen Dank.

**Comment by sirexeclp** [comment]
zum Thema Kontakt. Reicht es wenn wir da Adresse des Vereins und Email eintragen.
Haben wir ein Telefon?
Was genau ist mit c/o vertretungsberechtigter Vorstand gemeint?
Oder nennen wir einen Vorstand aber die Adresse des Vereins ?

**Comment by DrSkyfaR** [comment]
"c/o" bedeutet in dem Zusammenhang soviel wie = in Vertretung für: 
Also in meinem Fall im Verein "c/o Christopher Bodtke" = In Vertretung für den Verein Anoxinon e.V. - 1. Vorsitzender Christopher Bodtke. 


Aussehen kann sowas wie folgt 

Musterverein e.V.
c/o Max Mustermann, Max Mustermann 2, Max Mustermann 3 (je nachdem wie viele Vorstände es gibt)
Musterstraße 12345 
54321 Musterstadt
Telefon: (+01) 234 / 5678 9999 
Mail: postfach@example.de

Eine Telefonnummer werdet ihr ohnehin brauchen, alleine zwecks Webseite und TMG etc. entweder man besorgt sich dafür ne Prepaid Karte oder jemand im Vorstand opfert sich oder seine Nummer
