### ISSUE TITLE
Schöne Beitrittserklärung designen

### ISSUE THREAD

**Issue by chsterz** [Chaostreff-Potsdam/satzungsentwurf#9]
@pluehne

**Comment by chsterz** [comment]
Done, 
sourcen unter 
https://github.com/Chaostreff-Potsdam/office
fertige pdf unter
https://files.ccc-p.org/formulare/mitgliedsantrag.pdf

Danke, @pluehne

**Comment by pluehne** [comment]
Ups, hab vergessen, das zuzumachen :slightly_smiling_face:.
